version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: library_admin
      POSTGRES_PASSWORD: library_pass
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rust-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://library_admin:library_pass@db/library_db
    ports:
      - "8080:8080"
    depends_on:
      - db
